
set(CMAKE_SYSTEM_PROCESSOR "x86")
set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_VERSION "Generic")

set(CMAKE_SYSTEM_PREFIX_PATH "/usr")
set(CMAKE_SYSTEM_LIBRARY_PATH "/usr/lib32")
set(CMAKE_LIBRARY_PATH "${CMAKE_SYSTEM_LIBRARY_PATH}")


set(CMAKE_C_FLAGS "-m32" CACHE STRING "cflags")
